modelname: languagebind
basemodel: languagebind
_target_: src.model.languagebind.languagebindcir.languagebind_cir

ckpt_path: ${model.ckpt.path}

model:
  _target_: src.model.languagebind.languagebindcir.LanguageBindCir
  vit_model: "eva_clip_g"
  image_size: ${model.ckpt.image_size}
  drop_path_rate: 0
  use_grad_checkpoint: True
  vit_precision: "fp32"
  train_vit: False
  num_query_token: 32
  temperature: 0.07
  vit: "large"

  loss: ${model.loss}

  si_ti_weight: ${model.loss_terms.si_ti_weight}
  si_tc_weight: ${model.loss_terms.si_tc_weight}
  si_el_weight: 0
  si_att_weight: 0
